name: Build artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean jpackage --info

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: CRLauncher-${{ matrix.os }}
          path: build/dist

  build-linux:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-type: [ DEB, RPM]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install RPM packaging tools
        if: matrix.package-type == 'RPM'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Install DEB packaging tools
        if: matrix.package-type == 'DEB'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean jpackage -PlinuxPackageType=${{ matrix.package-type }} --info

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: CRLauncher-linux-${{ matrix.package-type }}
          path: build/dist